# Global settings applied to the whole site.
[build]
  publish = "build"
  command = "npm run build"

  # default env vars -- this should all point to staging
  environment = { LOAD_ENV = "staging" }

# These env vars are only applied for production deploys (ie master branch)
[context.production.environment]
  REACT_APP_LEADEREQ_ENV="production"
  REACT_APP_API_URL="https://chatspace_api.herokuapp.com"

# REDIRECTS - see https://www.netlify.com/docs/redirects/
# rewrite from /pagename to /pagename.html is done automatically
# fallback to 404.html is done automatically
